services:
  web:
    build: .
    container_name: post_real_container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  worker:
    build: .
    command: celery -A post_real.celery worker --loglevel=info
    #command: celery -A multi start w0 w1 post_real.celery --loglevel=info   #create multiple worker
    env_file:
      - .env
    depends_on:
      - web
  
  beat:
    build: .
    command: celery -A post_real beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - web

  flower:
    build: .
    command: celery -A post_real.celery flower --address=0.0.0.0 --port=5555 --basic_auth=username:password
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - worker
      - web